[lint]
select = [
    "ALL",
]

extend-ignore = [
    "ANN", # flake8-annotations
    "D", # pydocstyle
    "FBT", # flake8-boolean-trap
    "PGH", # pygrep-hooks
    # False positive, don't remove
    "S101", # Use of `assert` detected
    "SIM108", # Use ternary operator
    "A005",
    "T201", #  	print
]

[lint.mccabe]
max-complexity = 10
